
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)
// Create a new store instance.
const store = new Vuex.Store({
  state () {
    return {
      events:[
        {id:'1', Categorie:'Seniors Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'1èreDIVISION', startDate:'30/09/2022',endDate:'02/10/2022',departement:'89', lieux:'Saint Fargeau', pays:'France',info_comp:''},
        {id:'2', Categorie:'Seniors Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION Zone A', startDate:'01/07/2022',endDate:'03/07/2022',departement:'82', lieux:'Montech', pays:'France',info_comp:''},
        {id:'3', Categorie:'Seniors Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION Zone B', startDate:'01/07/2022',endDate:'03/07/2022',departement:'57', lieux:'Creutzwald', pays:'France',info_comp:''},
        {id:'4', Categorie:'Seniors Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION Zone C', startDate:'01/07/2022',endDate:'03/07/2022',departement:'70', lieux:'Ferrière les Scey', pays:'France',info_comp:''},
        {id:'5', Categorie:'Seniors Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'Coupe indiv. (ex GN)', startDate:'17/09/2022',endDate:'18/09/2022',departement:'28', lieux:'Douy', pays:'France',info_comp:''},
        {id:'6', Categorie:'Seniors Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'Finale des Clubs', startDate:'27/08/2022',endDate:'27/08/2022',departement:'', lieux:'', pays:'France',info_comp:''},
        {id:'7', Categorie:'Moulinet',type:'championnats nationaux', peche:'Anglaise',subtitle:'1èreDIVISION', startDate:'29/07/2022',endDate:'31/07/2022',departement:'', lieux:'', pays:'France',info_comp:''},
        {id:'8', Categorie:'Moulinet',type:'championnats nationaux', peche:'Anglaise',subtitle:'2èmeDIVISION Zone A', startDate:'10/06/2022',endDate:'12/06/2022',departement:'17', lieux:'Maran', pays:'France',info_comp:''},
        {id:'9', Categorie:'Moulinet',type:'championnats nationaux', peche:'Anglaise',subtitle:'2èmeDIVISION Zone B', startDate:'10/06/2022',endDate:'12/06/2022',departement:'27', lieux:'Bouafles', pays:'France',info_comp:''},
        {id:'10', Categorie:'Moulinet',type:'championnats nationaux', peche:'Anglaise',subtitle:'2èmeDIVISION Zone C', startDate:'10/06/2022',endDate:'12/06/2022',departement:'', lieux:'', pays:'France',info_comp:''},
        {id:'11', Categorie:'Jeunes Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'Championnat U25', startDate:'08/07/2022',endDate:'10/07/2022',departement:'90', lieux:'Brebotte', pays:'France',info_comp:''},
        {id:'12', Categorie:'Jeunes Mixte',type:'coupes de France', peche:'Coup classique',subtitle:'Coupe U20', startDate:'09/07/2022',endDate:'10/07/2022',departement:'90', lieux:'Brebotte', pays:'France',info_comp:''},
        {id:'13', Categorie:'Jeunes Mixte',type:'coupes de France', peche:'Coup classique',subtitle:'Coupe U15', startDate:'09/07/2022',endDate:'10/07/2022',departement:'90', lieux:'Brebotte', pays:'France',info_comp:''},
        {id:'14', Categorie:'Féminines Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'Championnat Féminin', startDate:'27/05/2022',endDate:'29/05/2022',departement:'58', lieux:'Prémery', pays:'France',info_comp:''},
        {id:'15', Categorie:'Masters et Vétérans Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'1èreDIVISION Vétérans', startDate:'12/08/2022',endDate:'14/08/2022',departement:'32', lieux:'Condom', pays:'France',info_comp:''},
        {id:'16', Categorie:'Masters et Vétérans Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'1èreDIVISION Masters', startDate:'12/08/2022',endDate:'14/08/2022',departement:'32', lieux:'Barran (lac de Castagnère)', pays:'France',info_comp:''},
        {id:'17', Categorie:'Masters et Vétérans Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION Zone A', startDate:'15/07/2022',endDate:'17/07/2022',departement:'32', lieux:'Condom et Castagnère', pays:'France',info_comp:''},
        {id:'18', Categorie:'Masters et Vétérans Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION Zone B', startDate:'15/07/2022',endDate:'17/07/2022',departement:'8', lieux:'Les Ayvelles', pays:'France',info_comp:''},
        {id:'19', Categorie:'Masters et Vétérans Mixte',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION Zone C', startDate:'15/07/2022',endDate:'17/07/2022',departement:'45', lieux:'Dampierre en Burly', pays:'France',info_comp:''},
        {id:'20', Categorie:'Masters et Vétérans Mixte',type:'coupes de France', peche:'Coup classique',subtitle:'Coupe V1 (55-65)', startDate:'24/09/2022',endDate:'25/90/2022',departement:'8', lieux:'Les Ayvelles', pays:'France',info_comp:''},
        {id:'21', Categorie:'Masters et Vétérans Mixte',type:'coupes de France', peche:'Coup classique',subtitle:'Coupe V2 (66-75)', startDate:'24/09/2022',endDate:'25/09/2022',departement:'8', lieux:'Les Ayvelles', pays:'France',info_comp:''},
        {id:'22', Categorie:'Masters et Vétérans Mixte',type:'coupes de France', peche:'Coup classique',subtitle:'Coupe V3 (+75)', startDate:'24/09/2022',endDate:'25/09/2022',departement:'8', lieux:'Les Ayvelles', pays:'France',info_comp:''},
        {id:'23', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'1èreDIVISION', startDate:'09/09/2022',endDate:'11/09/2022',departement:'85', lieux:'Sigournais (Rochereau)', pays:'France',info_comp:''},
        {id:'24', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'2èmeDIVISION Zone A', startDate:'17/06/2022',endDate:'19/06/2022',departement:'32', lieux:'Cazaubon', pays:'France',info_comp:''},
        {id:'25', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'2èmeDIVISION Zone B', startDate:'17/06/2022',endDate:'19/06/2022',departement:'27', lieux:'Vernon', pays:'France',info_comp:''},
        {id:'26', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'2èmeDIVISION Zone C', startDate:'17/06/2022',endDate:'19/06/2022',departement:'70', lieux:'Gray', pays:'France',info_comp:''},
        {id:'27', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'1èreDIVISION', startDate:'02/09/2022',endDate:'04/09/2022',departement:'3', lieux:'Isle et Bardais (Pirot)', pays:'France',info_comp:''},
        {id:'28', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'2èmeDIVISION Zone A', startDate:'03/05/2022',endDate:'05/05/2022',departement:'23', lieux:'Anzème', pays:'France',info_comp:''},
        {id:'29', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'2èmeDIVISION Zone B', startDate:'03/05/2022',endDate:'05/05/2022',departement:'8', lieux:'Sedan', pays:'France',info_comp:''},
        {id:'30', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'2èmeDIVISION Zone C', startDate:'03/05/2022',endDate:'05/05/2022',departement:'3', lieux:'Isle et Bardais (Pirot)', pays:'France',info_comp:''},
        {id:'31', Categorie:'Feeder',type:'coupes de France', peche:'Feeder',subtitle:'Coupe Individuelle', startDate:'',endDate:'',departement:'', lieux:'', pays:'France',info_comp:''},
        {id:'32', Categorie:'Feeder',type:'coupes de France', peche:'Feeder',subtitle:'Coupe Masters Vétérans', startDate:'15/10/2022',endDate:'16/10/2022',departement:'56', lieux:'Rieux', pays:'France',info_comp:''},
        {id:'33', Categorie:'Feeder',type:'coupes de France', peche:'Feeder',subtitle:'Coupe Jeunes et Femmes', startDate:'06/08/2022',endDate:'07/08/2022',departement:'89', lieux:'St Fargeau (Bourdon)', pays:'France',info_comp:''},
        {id:'34', Categorie:'Feeder',type:'championnats nationaux', peche:'Feeder',subtitle:'Championnat des Clubs', startDate:'',endDate:'',departement:'', lieux:'', pays:'France',info_comp:''},
        {id:'35', Categorie:'Corporatifs',type:'championnats nationaux', peche:'Coup classique',subtitle:'1èreDIVISION', startDate:'23/7/2022',endDate:'24/7/2022',departement:'89', lieux:'Saint Fargeau', pays:'France',info_comp:''},
        {id:'36', Categorie:'Corporatifs',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION', startDate:'25/6/2022',endDate:'26/06/2022',departement:'57', lieux:'Wittring', pays:'France',info_comp:''},
        {id:'37', Categorie:'Corporatifs',type:'coupes de France', peche:'Coup classique',subtitle:'Coupe individuelle', startDate:'03/09/2022',endDate:'03/09/2022',departement:'68', lieux:'Montreux-Vieux', pays:'France',info_comp:''},
        {id:'38', Categorie:'Corporatifs',type:'championnats nationaux', peche:'Coup classique',subtitle:'Championnat des Clubs', startDate:'4/9/2022',endDate:'04/09/2022',departement:'68', lieux:'Montreux-Vieux', pays:'France',info_comp:''},
        {id:'39', Categorie:'Handicapés',type:'championnats nationaux', peche:'Coup classique',subtitle:'1èreDIVISION', startDate:'30/09/2022',endDate:'2/10/2022',departement:'36', lieux:'St Georges sur Arnon', pays:'France',info_comp:''},
        {id:'40', Categorie:'Handicapés',type:'championnats nationaux', peche:'Coup classique',subtitle:'2èmeDIVISION', startDate:'29/04/2022',endDate:'01/05/2022',departement:'2', lieux:'Saint Quentin', pays:'France',info_comp:''},
        {id:'41', Categorie:'Handicapés',type:'coupes de France', peche:'Coup classique',subtitle:'Coupe Individuelle', startDate:'29/10/2022',endDate:'30/10/2022',departement:'51', lieux:'Epernay', pays:'France',info_comp:''},
        {id:'42', Categorie:'Carpe',type:'championnats nationaux', peche:'Carpe au coup',subtitle:'1èreDIVISION', startDate:'09/09/2022',endDate:'11/09/2022',departement:'88', lieux:'Socourt', pays:'France',info_comp:''},
        {id:'43', Categorie:'Carpe',type:'championnats nationaux', peche:'Carpe au coup',subtitle:'2èmeDIVISION Zone A', startDate:'04/06/2022',endDate:'06/06/2022',departement:'47', lieux:'Bruch', pays:'France',info_comp:''},
        {id:'44', Categorie:'Carpe',type:'championnats nationaux', peche:'Carpe au coup',subtitle:'2èmeDIVISION Zone B', startDate:'27/05/2022',endDate:'29/05/2022',departement:'76', lieux:'Saint Hellier', pays:'France',info_comp:''},
        {id:'45', Categorie:'Carpe',type:'championnats nationaux', peche:'Carpe au coup',subtitle:'2èmeDIVISION Zone C', startDate:'16/05/2022',endDate:'15/05/2022',departement:'71', lieux:'Romenay (carpo Bresse)', pays:'France',info_comp:''},
        {id:'46', Categorie:'Carpe',type:'coupes de France', peche:'Carpe au coup',subtitle:'QualificationsCoupe', startDate:'',endDate:'',departement:'', lieux:'', pays:'France',info_comp:''},
        {id:'47', Categorie:'Carpe',type:'coupes de France', peche:'Carpe au coup',subtitle:'Finale Coupe de France', startDate:'27/08/2022',endDate:'28/08/2022',departement:'16', lieux:'Fregeneuil', pays:'France',info_comp:''},
        {id:'48', Categorie:'Truite',type:'concours', peche:'Truite aux appâts naturels',subtitle:'Concours', startDate:'02/04/2022',endDate:'03/04/2022',departement:'30', lieux:'Besseges', pays:'France',info_comp:''},
        {id:'49', Categorie:'Truite',type:'concours', peche:'Truite aux appâts naturels',subtitle:'Concours', startDate:'09/05/2022',endDate:'10/04/2022',departement:'9', lieux:'Tarascon sur Ariège', pays:'France',info_comp:''},
        {id:'50', Categorie:'Truite',type:'concours', peche:'Truite aux appâts naturels',subtitle:'Concours', startDate:'14/05/2022',endDate:'15/05/2022',departement:'66', lieux:'Arles-sur-Tech', pays:'France',info_comp:''},
        {id:'51', Categorie:'Truite',type:'concours', peche:'Truite aux appâts naturels',subtitle:'Concours', startDate:'21/05/2022',endDate:'22/05/2022',departement:'38', lieux:'Pont deCheruy', pays:'France',info_comp:''},
        {id:'52', Categorie:'Truite',type:'championnats nationaux', peche:'Truite aux appâts naturels',subtitle:'Qualifs Championnat de France', startDate:'04/06/2022',endDate:'04/06/2022',departement:'33', lieux:'Preignac', pays:'France',info_comp:''},
        {id:'53', Categorie:'Truite',type:'concours', peche:'Truite aux appâts naturels',subtitle:'Concours', startDate:'11/06/2022',endDate:'12/06/2022',departement:'64', lieux:'Orthez', pays:'France',info_comp:''},
        {id:'54', Categorie:'Truite',type:'championnats nationaux', peche:'Truite aux appâts naturels',subtitle:'Finale Championnat de France', startDate:'25/06/2022',endDate:'26/06/2022',departement:'12', lieux:'Broquies', pays:'France',info_comp:''},
        {id:'55', Categorie:'Autres grandes épreuves',type:'concours', peche:'Coup classique',subtitle:'Pôle élite', startDate:'14/05/2022',endDate:'15/05/2022',departement:'57', lieux:'Creutzwald', pays:'France',info_comp:''},
        {id:'56', Categorie:'GARBOLINO',type:'concours', peche:'Coup classique',subtitle:'Trophée GARBOLINO Alsace', startDate:'12/03/2022',endDate:'13/03/2022',departement:'67', lieux:'Denis Marx', pays:'France',info_comp:''},
        {id:'57', Categorie:'GARBOLINO',type:'concours', peche:'Coup classique',subtitle:'GARBOLINO Cup', startDate:'23/07/2022',endDate:'24/07/2022',departement:'37', lieux:'Chemillé-sur-Indrois', pays:'France',info_comp:''},
        {id:'58', Categorie:'GARBOLINO',type:'concours', peche:'Coup classique',subtitle:'GARBOLINO Breizh Cup', startDate:'17/09/2022',endDate:'18/09/2022',departement:'35', lieux:'Martigné-Ferchaud', pays:'France',info_comp:''},
        {id:'59', Categorie:'GARBOLINO',type:'concours', peche:'Coup classique',subtitle:'Zombie GARBOLINO Cup', startDate:'24/09/2022',endDate:'25/09/2022',departement:'2', lieux:'Domaine de Chassemy', pays:'France',info_comp:''},
        {id:'60', Categorie:'GARBOLINO',type:'concours', peche:'Coup classique',subtitle:'GARBOLINO Day', startDate:'22/10/2022',endDate:'23/10/2022',departement:'37', lieux:'Rillé', pays:'France',info_comp:''},
        {id:'61', Categorie:'GARBOLINO',type:'concours', peche:'Coup classique',subtitle:'Winter league GARBOLINO', startDate:'28/12/2022',endDate:'30/12/2022',departement:'44', lieux:'St Philibert de Grand Leu', pays:'France',info_comp:''},
        {id:'62', Categorie:'SENSAS',type:'concours', peche:'Coup classique',subtitle:'Festival SENSAS', startDate:'09/04/2022',endDate:'10/04/2022',departement:'28', lieux:'Douy', pays:'France',info_comp:''},
        {id:'63', Categorie:'SENSAS',type:'concours', peche:'Coup classique',subtitle:'Challenge SENSAS CRAZY BAIT', startDate:'07/05/2022',endDate:'08/05/2022',departement:'88', lieux:'Socourt', pays:'France',info_comp:''},
        {id:'64', Categorie:'SENSAS',type:'concours', peche:'Coup classique',subtitle:'Challenge SENSAS Mixte', startDate:'08/10/2022',endDate:'09/10/2022',departement:'28', lieux:'Châteaudun', pays:'France',info_comp:''},
        {id:'65', Categorie:'SENSAS',type:'concours', peche:'Feeder',subtitle:'SENSAS FEEDER TECH', startDate:'22/10/2022',endDate:'23/10/2022',departement:'35-56', lieux:'Redon - Rieux', pays:'France',info_comp:''},
        {id:'66', Categorie:'international',type:'international', peche:'Truite aux appâts naturels',subtitle:'TRUITE AUX APPATS NATURELS NATIONS ET CLUBS', startDate:'28/05/2022',endDate:'29/05/2022',departement:'', lieux:'Pont de Cheruy/Rivière Bourbre', pays:'France',info_comp:'28ème FRANCE'},
        {id:'67', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'PECHE COUP VETERANS', startDate:'11/06/2022',endDate:'12/06/2022',departement:'', lieux:'Szeged - Maty-éri evezőspálya', pays:'Hongrie',info_comp:'14éme HONGRIE'},
        {id:'68', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'PECHE COUP MASTERS', startDate:'11/06/2022',endDate:'12/06/2022',departement:'', lieux:'Szeged - Maty-éri evezőspálya', pays:'Hongrie',info_comp:'4ème HUNGARY'},
        {id:'69', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'PECHE COUP HANDICAPES', startDate:'11/06/2022',endDate:'12/06/2022',departement:'', lieux:'Szeged - Maty-éri evezőspálya', pays:'Hongrie',info_comp:'23ėme HUNGARY'},
        {id:'70', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'PECHE COUP EUROPE', startDate:'25/05/2022',endDate:'26/05/2022',departement:'', lieux:'Coruche - Sorraia River', pays:'Portugal',info_comp:'26ème PORTUGAL'},
        {id:'71', Categorie:'international',type:'international', peche:'Feeder',subtitle:'FEEDER NATIONS', startDate:'',endDate:'',departement:'', lieux:'', pays:'',info_comp:''},
        {id:'72', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'PECHE COUP CLUBS', startDate:'23/07/2022',endDate:'24/05/2022',departement:'', lieux:'Ronquières - Canal Charleroi-Bruxelles', pays:'Belgique',info_comp:'41ème BELGIQUE'},
        {id:'73', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'"PECHE COUP JEUNES U15 - U20 - U25"', startDate:'06/08/2022',endDate:'07/08/2022',departement:'', lieux:'Radece - Rivière Sava', pays:'Slovenie',info_comp:'SLOVENIE'},
        {id:'74', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'PECHE COUP FEMMES', startDate:'20/08/2022',endDate:'21/08/2022',departement:'', lieux:'Gravelines', pays:'France',info_comp:'28ème FRANCE'},
        {id:'75', Categorie:'international',type:'international', peche:'Coup classique',subtitle:'PECHE COUP NATIONS', startDate:'10/09/2022',endDate:'11/09/2022',departement:'', lieux:'Osijek - Stara Drava Bilje', pays:'Croatie',info_comp:'68ème CROATIE'},
        {id:'76', Categorie:'international',type:'international', peche:'Feeder',subtitle:'MASTER FEEDER', startDate:'08/10/2022',endDate:'09/10/2022',departement:'', lieux:'Badajoz - Rivière Guadiana', pays:'Espagne',info_comp:'1ère ESPAGNE'},
        {id:'77', Categorie:'international',type:'international', peche:'Feeder',subtitle:'FEEDER CLUBS', startDate:'09/04/2022',endDate:'10/04/2022',departement:'', lieux:'Adria Canal Biaco', pays:'Italie',info_comp:'5eme ITALIE'},
        {id:'79', Categorie:'Assemblée générale',type:'AG', peche:'',subtitle:'Assemblée générale', startDate:'25/03/2022',endDate:'25/03/2022',departement:'', lieux:'VISIOCONFERENCE', pays:'France',info_comp:''},
        {id:'80', Categorie:'Assemblée annuelle Eau Douce',type:'AG', peche:'',subtitle:'Assemblée annuelle Eau Douce', startDate:'06/03/2022',endDate:'06/03/2022',departement:'', lieux:'BOURGES', pays:'France',info_comp:''},
        {id:'81', Categorie:'Assemblée  annuelle TRUITE',type:'AG', peche:'',subtitle:'Assemblée  annuelle TRUITE', startDate:'24/02/2022',endDate:'24/02/2022',departement:'', lieux:'VISIOCONFERENCE', pays:'France',info_comp:''},
        {id:'00', Categorie:'milestone',type:'today', peche:'',subtitle:'', startDate:'23/03/2022',endDate:'23/03/2022',departement:'', lieux:'', pays:'',info_comp:''},
      ]   
      }
  }
})

export default store